LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libqc-opt
LOCAL_MODULE_OWNER := qcom
LOCAL_SRC_FILES_64 := proprietary/vendor/lib64/libqc-opt.so
LOCAL_SRC_FILES_32 := proprietary/vendor/lib/libqc-opt.so
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MODULE_PATH_32 := $(2ND_TARGET_OUT_SHARED_LIBRARIES)
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libqc-skia
LOCAL_MODULE_OWNER := qcom
LOCAL_SRC_FILES_64 := libs/arm64-v8a/libqc-skia.a
LOCAL_SRC_FILES_32 := libs/armeabi-v7a/libqc-skia.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MODULE_PATH_32 := $(2ND_TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)
