BUILD_DESCRIPTION=e1sxxx-user 14 UP1A.231005.007 S921BXXS8BYG2 release-keys
BUILD_FINGERPRINT=samsung/e1sxxx/e1s:14/UP1A.231005.007/S921BXXS8BYG2:user/release-keys
MANUFACTURER_NAME=samsung
PRODUCT_NAME=SM-S921B
BUILD_SECURITY_PATCH_DATE=2025-07-01
BUILD_TAGS=release-keys
BUILD_TYPE=user
BUILD_VERSION_RELEASE=14
DEBUGGABLE=0
