LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libqc-art
LOCAL_MODULE_OWNER := qcom
LOCAL_SRC_FILES_64 := libs/arm64-v8a/libqc-art.a
LOCAL_SRC_FILES_32 := libs/armeabi-v7a/libqc-art.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MODULE_PATH_32 := $(2ND_TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := libqc-art-compiler
LOCAL_MODULE_OWNER := qcom
LOCAL_SRC_FILES_64 := libs/arm64-v8a/libqc-art-compiler.a
LOCAL_SRC_FILES_32 := libs/armeabi-v7a/libqc-art-compiler.a
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE_PATH_64 := $(TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MODULE_PATH_32 := $(2ND_TARGET_OUT_STATIC_LIBRARIES)
LOCAL_MULTILIB := both
include $(BUILD_PREBUILT)
