PRODUCT_PACKAGES += \
    MotCamera2

PRODUCT_COPY_FILES := \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libDepthBokehEffect.so:system/lib/libDepthBokehEffect.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libFNVfbEngineHAL.so:system/lib/libFNVfbEngineHAL.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libMobileOcrEngine.so:system/lib/libMobileOcrEngine.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libMotDoF.so:system/lib/libMotDoF.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libSNPE.so:system/lib/libSNPE.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libSNPExecutor.so:system/lib/libSNPExecutor.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libarcsoft_agegender_estimation.so:system/lib/libarcsoft_agegender_estimation.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libarcsoft_beautyshot.so:system/lib/libarcsoft_beautyshot.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libarcsoft_dualcam_refocus.so:system/lib/libarcsoft_dualcam_refocus.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libbsDepthWrapper_01_00_000.so:system/lib/libbsDepthWrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libc++_shared.so:system/lib/libc++_shared.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libclearsight.so:system/lib/libclearsight.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libclearsight_wrapper_01_00_000.so:system/lib/libclearsight_wrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libddm_wrapper_01_00_000.so:system/lib/libddm_wrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libdualcameraddm.so:system/lib/libdualcameraddm.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libframe_stack_wrapper_morpho_v4.so:system/lib/libframe_stack_wrapper_morpho_v4.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libframe_stack_wrapper_morpho_v5.so:system/lib/libframe_stack_wrapper_morpho_v5.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libgif.so:system/lib/libgif.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/liblenovo_panorama.so:system/lib/liblenovo_panorama.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-common.so:system/lib/libmcf-common.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-foundation.so:system/lib/libmcf-foundation.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-foundation2.so:system/lib/libmcf-foundation2.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-jni.so:system/lib/libmcf-jni.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-local.so:system/lib/libmcf-local.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf-qc-fd-offline.so:system/lib/libmcf-qc-fd-offline.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcf.so:system/lib/libmcf.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmcfutils.so:system/lib/libmcfutils.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_cinema_graph.so:system/lib/libmorpho_cinema_graph.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_defocusface.so:system/lib/libmorpho_defocusface \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_image_stab5.so:system/lib/libmorpho_image_stab5.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_image_stabilizer4.so:system/lib/libmorpho_image_stabilizer4.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_panorama_gp3.so:system/lib/libmorpho_panorama_gp3.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_sensor_fusion.so:system/lib/libmorpho_sensor_fusion.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmorpho_super_resolution.so:system/lib/libmorpho_super_resolution.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmotioncore_01_00_000.so:system/lib/libmotioncore_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libmpbase.so:system/lib/libmpbase.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/liboffline_fd_wrapper_01_00_000.so:system/lib/liboffline_fd_wrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libopenssh.so:system/lib/libopenssh.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/librefocus_image_wrapper_01_00_000.so:system/lib/librefocus_image_wrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libremosaic_tuning.so:system/lib/libremosaic_tuning.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libremosaic_wrapper.so:system/lib/libremosaic_wrapper.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libremosaiclib.so:system/lib/libremosaiclib.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe-android.so:system/lib/libsnpe-android.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe_adsp.so:system/lib/libsnpe_adsp.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe_dsp_domains.so:system/lib/libsnpe_dsp_domains.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe_dsp_domains_skel.so:system/lib/libsnpe_dsp_domains_skel.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe_dsp_skel.so:system/lib/libsnpe_dsp_skel.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsnpe_dsp_v65_domains_skel.so:system/lib/libsnpe_dsp_v65_domains_skel.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsuper_resolution_wrapper_morpho_v2.so:system/lib/libsuper_resolution_wrapper_morpho_v2.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsymphony-cpu.so:system/lib/libsymphony-cpu.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libsymphonypower.so:system/lib/libsymphonypower.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libubifocus_wrapper_01_00_000.so:system/lib/libubifocus_wrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libzxing_01_00_000.so:system/lib/libzxing_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm/libzxingwrapper_01_00_000.so:system/lib/libzxingwrapper_01_00_000.so \
    vendor/extra/oem-cameras/MotCamera2/lib/arm64/librcfw.so:system/lib64/librcfw.so
